# Terms of Service

Welcome to Infinity AI!

These Terms of Service ("Terms") govern your use of Infinity AI mobile application ("the App") provided by Mused LLC ("us"). By downloading, accessing, or using the App, you agree to be bound by these Terms. If you do not agree with any part of these Terms, please refrain from using the App.

## App Usage
a. The App provides a chat interface powered by Chat GPT technology in a web view and offers a library of premade prompts for users to interact with the system.

b. You understand and acknowledge that the responses generated by Chat GPT are based on a machine learning model and may not always be accurate or reliable. We are not responsible for any actions or decisions taken based on the information provided by the App.

c. You agree to use the App solely for lawful purposes and in compliance with all applicable laws and regulations.

## Intellectual Property
a. The App and all related content, including but not limited to text, graphics, images, logos, and software, are the property of Mused LLC or its licensors and are protected by intellectual property laws. You may not copy, modify, distribute, or reproduce any part of the App without our prior written consent.

b. By using the App, you grant us a non-exclusive, worldwide, royalty-free, and sub-licensable license to use, reproduce, distribute, and display any content or information you provide through the App for the purpose of operating and improving the App.

Privacy
a. Your privacy is important to us. Please refer to our Privacy Policy [provide a link to your Privacy Policy] to understand how we collect, use, and protect your personal information.

## Third-Party Links and Services
a. The App may contain links to third-party websites or services that are not owned or controlled by us. We are not responsible for the content, privacy policies, or practices of any third-party websites or services. You acknowledge and agree that we shall not be liable for any damages or losses caused by your use of such third-party websites or services.

## Limitation of Liability
a. To the maximum extent permitted by applicable law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or in connection with your use of the App, including but not limited to any errors or inaccuracies in the responses generated by Chat GPT.

## Changes to the Terms
a. We reserve the right to modify or update these Terms at any time without prior notice. The updated Terms will be effective upon posting. Your continued use of the App after the posting of any changes constitutes your acceptance of the modified Terms.

## Governing Law
a. These Terms shall be governed by and construed in accordance with the laws of the state of Maryland, United States, without regard to its conflict of law principles.

## Contact Us
If you have any questions or concerns regarding these Terms or the App, please contact us at [Your contact information].

By using the App, you acknowledge that you have read, understood, and agreed to these Terms of Service.
